config/routes.rb
Rails.application.routes.draw do
  root 'pages#home' #get 'pages/home'
  get 'team', to: 'pages#team'
  get 'contact', to: 'pages#contact'
  get 'welcome/:first_name', to: 'pages#hidden_link'
  get '/gossip/:id', to: 'pages#gossip_display', as: 'gossip'
  get 'user/:id', to: 'pages#user_profil', as: 'user'

  get '/welcome', to: 'pages#welcome'
  get '/welcome/:name', to: 'dynamic_pages#welcome'
  get 'form_filled', to: 'pages#form_filled'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :join_tags_gossips
  has_many :tags, through: :join_tags_gossips
end

app/models/join_tags_gossip.rb
class JoinTagsGossip < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :sender, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_tags_gossips
  has_many :gossips, through: :join_tags_gossips
end

app/models/user.rb
class User < ApplicationRecord
  has_many :gossips
  belongs_to :city
  has_many :sent_messages, foreign_key: "sender_id", class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: "recipient_id", class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dynamic_pages_controller.rb
class DynamicPagesController < ApplicationController
	def welcome
		@user_name = params['name']
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def team
  end

  def contact
  end

  def hidden_link
  end

  def gossip_display
    @gossip = Gossip.find(params['id'])
  end

  def user_profil
    @user = User.find(params['id'])
  end

  def form_filled
  end
  
  def welcome
    @user_name = params['name']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gossip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js">

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="collapse navbar-collapse" id="navbarColor08">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to 'Home', root_path, class: 'element' %>
            </li>
            <li class="nav-item active">
              <%= link_to "S'identifier", welcome_path, class: 'element' %>
            </li>
            <li class="nav-item active">
              <%= link_to 'Contact', contact_path, class: 'element' %>
            </li>
            <li class="nav-item active">
              <%= link_to 'Team', team_path, class: 'element' %>
            </li>
          </ul>
      </div>
    </nav>

    <footer>
    
    </footer>

    <%= yield %>
  </body>
</html>

app/views/pages/contact.html.erb
<body>
	
	</br></br>
	<h1>Voici notre page contact lol mdr</h1>

	</br></br>
	<p>01 47 20 00 01 ou 3615 ULLA</p>

</body>

app/views/pages/gossip_display.html.erb
<h1>You are looking at gossip n°<%= @gossip.id %></h1>
<p>
	<a href="<%= user_path(@gossip.user.id) %>"><%=@gossip.user.first_name%> <%=@gossip.user.last_name%></a><br />
	<p>Title : <%=@gossip.title%></p><br />
	<p>Content : <%=@gossip.content%></p><br />

</p>

app/views/pages/home.html.erb
<% i = 1 %>
		<div class="flex-parent d-flex flex-wrap justify-content-around">
		<% Gossip.all.each do |current_gossip| %>
		<div class="card" style="width: 45rem;">
			<div class="card-header">Gossip n°<%=current_gossip.id%></div>

			<div class="card-body">
				<h5 class="card-title text-muted">Posté par <a href="<%= user_path(current_gossip.user.id) %>"><%=current_gossip.user.first_name%> <%=current_gossip.user.last_name%></a></h5>
				<p class="card-text"><%current_gossip.content%></p>
				<div class="text-center">
					<a href="<%= gossip_path(current_gossip.id) %>" class="btn btn-primary">Voir le gossip</a>
				</div>
			</div>

		</div>
		<%puts "i=#{i}"%>
		<% if i==5 %>
		<% i = 1 %>
		<% end %>
		<% i += 1 %>
		<% end %>
</div>

app/views/pages/team.html.erb
<body>
	
	</br></br>
	<h1>Voici notre page équipe lol mdr</h1>

	</br></br>
	<p>Team champenoise, première sur les bulles - surtout dans le code (niveau proche de 0, t'as capté ?)</p>

</body>

app/views/pages/user_profil.html.erb
<!-- <h1>Profil n°<%= @user.id %></h1>
<p>
	<%= @user.first_name %><br />
	<%= @user.last_name%><br />
	<%= @user.age%><br />
	<%= @user.email%><br />
	<%= @user.created_at%><br />
	<%= @user.updated_at%><br />


</p> -->
<div class="global">
	<div class="user-info">
			<p class="name"><%= @user.first_name %> <%= @user.last_name %></p>
			<p class="created_at">Inscrit depuis le : <%= @user.created_at.to_s.split(" ")[0...-1].join(" ") %></p>
		</div>
	</div>
	<div class="gossips">
		<div class="presentation">
			<p>Les gossips de <%= @user.first_name %></p>
		</div>
		<% @user.gossips.each do |current_gossip| %>
		<div class="gossip">
			<p>Title : <%= current_gossip.title %></p>
			<p>Content : <%= current_gossip.content %></p>
		</div>
		<% end %>
	</div>
</div>

app/views/pages/welcome.html.erb
<body>
	
	</br></br>
	<h1>Bienvenue à toi, <%= @user_name ? @user_name : "... mais qui es-tu ?" %></h1>
	
	<p>Ici c'est notre super site de potins !</p>

	<% if @user_name %>
		<p>Ravi de t'avoir parmi nous !</p>
	<% else %>
		<p>Pour accéder à ta propre page super personnalisée, il te suffit d'indiquer 
		ton prénom dans l'URL après "/welcome"<br>
		Exemple : je m'appelle Didier, je rajoute "/didier" à la fin de l'URL - et le tour est joué !</p>
	<% end %>

</body>